version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8889:80
    depends_on:
      - app
    container_name: ProfiRU_nginx

  app:
    build:
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: ProfiRU_app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 8101:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    container_name: ProfiRU_db